# Generated by Django 5.0.6 on 2024-08-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("class_period", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="class_period",
            old_name="class_id",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="class_period",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
