# Generated by Django 3.2.12 on 2024-06-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher_age', models.PositiveIntegerField()),
                ('teacher_id', models.PositiveIntegerField()),
                ('teacher_course', models.CharField(max_length=20)),
                ('teacher_class', models.CharField(max_length=20)),
                ('teacher_description', models.TextField()),
                ('teacher_occupation', models.CharField(max_length=20)),
                ('teacher_salary', models.PositiveIntegerField()),
                ('teacher_hobby', models.TextField()),
                ('teacher_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
            options={
                'ordering': ['teacher_name'],
            },
        ),
    ]
