# Generated by Django 5.0.6 on 2024-07-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_class',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_headshot',
            field=models.ImageField(default='default_teacher_headshot.jpg', upload_to=''),
        ),
    ]
