# Generated by Django 5.0.6 on 2024-08-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_classes_course_tought_classes_name_and_more'),
        ('teacher', '0003_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(to='classes.classes'),
        ),
    ]
