# Generated by Django 3.2.12 on 2024-06-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='id',
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
