# Generated by Django 5.0.6 on 2024-07-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20240619_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='course_tought',
        ),
        migrations.AddField(
            model_name='classes',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classes',
            name='course_day_of_week',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3),
        ),
        migrations.AlterField(
            model_name='classes',
            name='equipment',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='classes',
            name='seating_arrangement',
            field=models.JSONField(default=dict),
        ),
    ]
