# Generated by Django 3.2.12 on 2024-06-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_instructor', models.CharField(max_length=20)),
                ('course_department', models.CharField(max_length=20)),
                ('course_syllabus', models.CharField(max_length=20)),
                ('course_code', models.PositiveSmallIntegerField()),
                ('course_assigment', models.CharField(max_length=20)),
                ('course_level', models.CharField(max_length=20)),
                ('course_description', models.TextField()),
                ('course_exams', models.CharField(max_length=20)),
                ('course_duration', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
