# Generated by Django 5.0.6 on 2024-08-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_duration',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_instructor',
        ),
    ]
