# Generated by Django 5.0.6 on 2024-08-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('student', '0005_remove_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
