# Generated by Django 5.0.6 on 2024-08-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_courses_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_duration',
            field=models.CharField(default='Default name', max_length=100),
        ),
    ]
