# Generated by Django 5.0.6 on 2024-08-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_instructor',
        ),
    ]
