# Generated by Django 5.0.6 on 2024-08-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courses_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_instructor',
        ),
    ]
