# Generated by Django 5.0.6 on 2024-08-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_courses_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.CharField(max_length=100),
        ),
    ]
