# Generated by Django 5.0.6 on 2024-08-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courses_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_duration',
        ),
    ]
