# Generated by Django 5.0.6 on 2024-08-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_classes_course_tought_classes_name_and_more'),
        ('student', '0003_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(to='classes.classes'),
        ),
    ]
