# Generated by Django 5.0.6 on 2024-08-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
